### ISSUE TITLE
.gitignore anlegen

### ISSUE THREAD

**Issue by nipafx** [THBingen/THProjectX#12]
(Bitte diesen Text editieren und Aufgabe beschreiben.)

**Comment by nipafx** [comment]
[Die existierende `.gitignore`](https://github.com/THBingen/THProjectX/blob/master/.gitignore) ist leer.

**Comment by zvenon** [comment]
.gitignore anlegen und erweitern, sodass Git nicht relevante Dateien ignorieren bzw außer Acht lassen kann.
Hierzu gitignore erweitern mit bsplw: *.iml ; .idea/ für IntelliJ  und target/  für Maven
