### ISSUE TITLE
Erstellen einer Schienennetzsimulation

### ISSUE THREAD

**Issue by Matze93** [THBingen/THProjectX#16]
bestehend aus Schienennetz(1) welches aus Eisenbahnsegmenten(5) mit einer Kapazität von jeweils (3) Zügen aufgebaut ist. Maximale Kapazität Züge (15). Alle Züge stellen Ansprüche auf welchem Segment sie fahren wollen. Das Netz muss nun die Ansprüche mit der Kapazität jeden Segments vergleichen. Kommt es auf einem Segment zur Überschreitung (4 oder mehr Züge) muss eine Verspätung aller Züge ausgegeben werden zB. mit "false", andernfalls keine Verzögerung "true". 
Klassen für Züge und Netzwerk sinnvoll. Methoden für das aufzählen der Züge, deren Ansprüche, Vergleiche der Kapazität etc.

**Comment by zvenon** [comment]
In den Issues #17 #20 ist zu erkennen, dass wir eine Train Class, RailSegment Class erstellen. Ich glaube wir sollten diskutieren, was in den jeweiligen Klassen stehen muss. 
Train Class:
Soll eine Liste aus Zügen enthalten enthalten, die alle fahren wollen und anhand eine Zeitplans angeben auf welchen Segment sie fahren wollen. 
RailSegment Class:
Enthält 5 Listen  (bsp Segments1-5) denen die Anzahl von Zügen hinzugefügt wird, die in der Train Class angeben auf jenem Segment(entsprechende Liste) fahren zu wollen.
Anschließend wird die Anzahl der Züge in den jeweiligen Listen mit einer Kapazität (Aufgabenstellung) verglichen. Übersteigt sie diese -> Verspätung.
Glaube damit sollten wir anfangen. 
Was meint ihr?? @Matze93 @RobinGoetz @FlixsTHB
