### ISSUE TITLE
Schreiben der Szenariofunktion

### ISSUE THREAD

**Issue by Matze93** [THBingen/THProjectX#18]
Simulation mit 12 Zügen im Schienennetz. Ausgabe nach der Simulation welche Züge fahren oder nicht fahren. Externe Funktion mittels Univocity Parser zum erstellen einer CSV-file die von main aufgerufen wird.

**Comment by RobinGoetz** [comment]
Beim derzeitigen Code ist die Main.kt unsere Szenario Funktion.

**Comment by Matze93** [comment]
erledigt

**Comment by nipafx** [comment]
Bitte schließt Issues erst, wenn der dazugehörige PR gemergt ist.
