### ISSUE TITLE
Decide on a language

### ISSUE THREAD

**Issue by zvenon** [THBingen/THProjectX#2]
we have to decide the language we want to use (till we've done this, I will write in english)

- conversations on Github
- comments (Code)

This has to be document in the README.md

**Comment by FlixSR** [comment]
Unterhaltung und Kommentar bitte in Deutsch

**Comment by Matze93** [comment]
okay passt.

**Comment by RobinGoetz** [comment]
Dem stimme ich zu. Comments und Conversation auf Deutsch.

**Comment by zvenon** [comment]
Top, dann wäre das geklärt 👍 Ändere die README.md demenstprechend ab.
