### ISSUE TITLE
Univocity- Parsers Update

### ISSUE THREAD

**Issue by RobinGoetz** [THBingen/THProjectX#21]
Matthias fragte:
"auf der univocity Seite steht dass es mittlerweile Version 2.5.8 gibt. Denkt ihr wir sollten die in der pom verwenden? oder ist das nicht wichtig?"

**Comment by Matze93** [comment]
Danke für die Korrektur, und sorry für die blöd gewählte Platzierung meiner Frage

**Comment by nipafx** [comment]
Ja, könnte man machen. Sehe nichts, was dagegen spricht.
