### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by zvenon** [THBingen/THProjectX#27]
Kurze Erläuterung zur Zug-Simulation und Update .jar-Datei in der README.md

**Comment by nipafx** [comment]
Welcher PR gehörte hierzu? Das sollte am Issue vermerkt werden. (Geht am einfachsten, wenn man im PR das Issue erwähnt.)

**Comment by zvenon** [comment]
Wurde auf dem Branch "Code2.0_neu" bearbeitet und mit PR #25 erledigt.
