### ISSUE TITLE
Release 2.0 jar-file kann nicht ausgeführt werden

### ISSUE THREAD

**Issue by Matze93** [THBingen/THProjectX#33]
@nicolaiparlog beim überprüfen ist uns aufgefallen dass sich die jar von Release 2.0 nicht ausführen lässt. Haben schon einige Änderungen ausprobiert z.B. Änderung des Namens der Main.kt, aber das Problem besteht weiterhin. Im Code lässt sich jedoch alles problemlos runnen. Haben Sie noch eine Idee was der Grund dafür sein könnte? Über Ihre Hilfe sind wir sehr dankbar!
![grafik](https://user-images.githubusercontent.com/29333296/32230082-a6263a9a-be52-11e7-9876-bb5a50253977.png) so sieht die Fehlermeldung aus.

**Comment by nipafx** [comment]
Gut aufgepasst. Die Meldung ist relativ eindeutig: MainKt Kann nicht gefunden werden. Der Grund dafür ist dass die Klasse genau genommen, nicht so heißt. In der POM steht folgendes:

```xml
<main.class>MainKt</main.class>
```

Die `Main`-Klasse ist aber im Paket `rail_simulation` und das muss ihrem Namen vorangestellt werden:

```xml
<main.class>rail_simulation.MainKt</main.class>
```

Wenn ihr das behoben macht, macht bitte ein Release 2.1 mit der korrigierten POM.

**Comment by zvenon** [comment]
Super, danke dir 👌  
Hatten als versucht das package hier irgendwie  `<sourceDirectory>${project.basedir}/src/main/kotlin/</sourceDirectory>` einzubauen
Release 2.1  @FlixsTHB
