### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by zvenon** [THBingen/THProjectX#35]
Erweiterung der README.md
-  Erklärung für Benutzer, wie das Programm verwendet werden kann --> Update der Navigation
-  Erläuterung zum Programm --> kurze Dokumentation zum Programmablauf

**Comment by FlixSR** [comment]
Die README.md wird auf den aktuellen Stand unseres Projektes gebracht.
Die erfolgreichen Elemente hin zum 3. Release werden hinzugefügt.
