### ISSUE TITLE
Erstellung eines Kotlin/Maven Projektes mit "HelloWorld" PrintOut

### ISSUE THREAD

**Issue by FlixSR** [THBingen/THProjectX#6]
Erstellung eines Kotlin/Maven Projektes mit einer Klasse "Hallo World.kt" und dem printOut"Hello,World."

**Comment by FlixSR** [comment]
Durch den PR "Stufe1 Print 'HelloWorld'" ist dieses Issue erledigt

**Comment by nipafx** [comment]
Der PR hat keine POM hinzugefügt und dieses Issues deswegen nicht erledigt.

Pull Requests und Issues referenziert man am besten durch `#<nr>`, in diesem Fall also #7.
