### ISSUE TITLE
Travis einbinden

### ISSUE THREAD

**Issue by zvenon** [THBingen/THProjectX#9]

**Comment by FlixSR** [comment]
@nicolaiparlog Wie läuft das mit der Einbindung in Travis jetzt ab? Müssen wir noch irgendetwas machen?

**Comment by nipafx** [comment]
Jemand von euch müsste einer Mail bekommen haben, die zur Aktivierung von Travis auffordert. Meldet euch, wenn ihr das gemacht habt.

**Comment by FlixSR** [comment]
Hab Travis Zugriff gewährt.

**Comment by Matze93** [comment]
@FlixsTHB damit ist es dann auch erledigt oder? oder muss jeder Zugriff gewähren

**Comment by nipafx** [comment]
Einer scheint zu reichen - konnte Travis anschalten (siehe #19).
